# Generated by Django 3.2.9 on 2022-07-07 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30, verbose_name='доменное имя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='название сайта')),
                ('original_link', models.URLField(max_length=1000, verbose_name='оригинальная ссылка')),
                ('short_link', models.CharField(max_length=50, verbose_name='сокращенная ссылка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener_app.profile')),
            ],
        ),
    ]
