# Generated by Django 3.2.9 on 2022-07-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='название сайта')),
                ('original_link', models.URLField(verbose_name='оригинальная ссылка')),
                ('short_link', models.URLField(verbose_name='сокращенная ссылка')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener_app.profile')),
            ],
        ),
    ]
