# Generated by Django 3.2.9 on 2022-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_shortlink_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
