# Generated by Django 3.2.9 on 2022-07-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0002_shortlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='domain',
            field=models.CharField(max_length=30, verbose_name='доменное имя'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short_link',
            field=models.CharField(max_length=50, verbose_name='сокращенная ссылка'),
        ),
    ]
