# Generated by Django 3.2.9 on 2022-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0003_auto_20220707_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='site_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='название сайта'),
        ),
    ]
