# Generated by Django 3.2.9 on 2022-07-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_app', '0004_alter_shortlink_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='site_name',
            field=models.CharField(max_length=50, verbose_name='название сайта'),
        ),
    ]
